# Use Node.js image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json first to leverage Docker cache
COPY package.json package-lock.json ./

# Install dependencies, including Supabase
RUN npm install

RUN npm install axios

# Install the Supabase client library (if not already included in package.json)
RUN npm install @supabase/supabase-js

RUN npm install @fortawesome/react-fontawesome

RUN npm install @fortawesome/free-solid-svg-icons

# Copy the rest of your application code
COPY . .



# Expose the port your app runs on
EXPOSE 3000

# Start the application in development mode
CMD ["npm", "run", "dev"]